- hosts: web
  tasks:
    - name: Install dumb init
      get_url:
        dest: /usr/bin/dumb-init
        url: https://github.com/Yelp/dumb-init/releases/download/v1.0.2/dumb-init_1.0.2_amd64
        mode: 0775
        validate_certs: no

    - name: Install EPEL
      yum: name=epel-release state=latest
    - name: Install Flask
      yum: name=python-flask state=latest
    - name: Install Jinja2
      yum: name=python-jinja2 state=latest
    - name: Create Flask User
      user: name=flaskapp state=present createhome=yes home=/flaskapp group=root
    - name: Create /flaskapp with correct permissions
      file: name=/flaskapp state=directory owner=flaskapp group=root mode=0777
      remote_user: flaskapp
    - name: Copy The Application
      copy:
       src: flask-helloworld/
       dest: /flaskapp/
       owner: flaskapp
       mode: 0777
